PROJECT_ID = 'base-dos-dados-395523'
DIR_DADOS_ORIGINAIS = 'dados/originais'
DIR_DADOS_TRATADOS = 'dados/tratados'

DIR_GRAFICOS_TABELA = 'graficos/tabela'
DIR_GRAFICOS_BARRA = 'graficos/barra'
DIR_GRAFICOS_DISPERSAO = 'graficos/dispersao'

DATASET_ID_IDEB  = 'br_inep_ideb'
DATASET_ID_INDICADORES  = 'br_inep_indicadores_educacionais'

PATH_IDEB = f'{DIR_DADOS_ORIGINAIS}/{DATASET_ID_IDEB}.csv'
PATH_INDICADORES_BRASIL_ORIGINAL = f'{DIR_DADOS_ORIGINAIS}/{DATASET_ID_INDICADORES}__brasil.csv'
PATH_INDICADORES_UF_ORIGINAL = f'{DIR_DADOS_ORIGINAIS}/{DATASET_ID_INDICADORES}__uf.csv'

PATH_INDICADORES_BRASIL_TRATADO = f'{DIR_DADOS_TRATADOS}/{DATASET_ID_INDICADORES}__brasil__tratado.csv'
PATH_INDICADORES_UF_TRATADO = f'{DIR_DADOS_TRATADOS}/{DATASET_ID_INDICADORES}__uf__tratado.csv'

